services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: orbit-frontend-image
    container_name: orbit-frontend-container
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
